[package]
name = "graph-anns"
version = "0.1.0"
# edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.23.0"
tinyset = "0.4.2"
parking_lot = "0.11.2"
atomic_float = "0.1.0"

[profile.release]
debug = true
